# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.merfisheyes.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.merfisheyes.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.merfisheyes.name }}
spec:
  replicas: {{ .Values.merfisheyes.numOfPods }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.merfisheyes.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.merfisheyes.name }}
    spec:
      containers:
        - name: {{ .Values.merfisheyes.name }}
          image: {{ .Values.merfisheyes.image }}:{{ .Values.merfisheyes.imageTag }}
          imagePullPolicy: {{ .Values.merfisheyes.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.merfisheyes.command }}
          command:
{{ toYaml .Values.merfisheyes.command | indent 12 }}
          {{- end }}
          {{- if .Values.merfisheyes.args }}
          args:
{{ toYaml .Values.merfisheyes.args | indent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.merfisheyes.service.port }}
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /merfisheyes/viewer
              port: {{ .Values.merfisheyes.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /merfisheyes/viewer
              port: {{ .Values.merfisheyes.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
{{- end }}
